controllers:
    resource: ../../src/Controller/
    type: annotation

services:
    resource: ../../src/Service/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
