<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQWTaAw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQWTaAw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQWTaAw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQWTaAw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSQWTaAw\App_KernelDevDebugContainer([
    'container.build_hash' => 'SQWTaAw',
    'container.build_id' => 'db2eac19',
    'container.build_time' => 1605627555,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQWTaAw');
