<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrg3gEG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrg3gEG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOrg3gEG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOrg3gEG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOrg3gEG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Org3gEG',
    'container.build_id' => 'da18bf87',
    'container.build_time' => 1605546594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrg3gEG');
