<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJp7KxMA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJp7KxMA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJp7KxMA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJp7KxMA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJp7KxMA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jp7KxMA',
    'container.build_id' => 'd4f94d1f',
    'container.build_time' => 1607964115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJp7KxMA');
